name: {{ cookiecutter.conda_environment_name }}
channels:
  - defaults
  - pscondaenvs
dependencies:
  - pscondaenvs=1.2.4
  - python={{ cookiecutter.python_version }}
  - python-graphviz=0.8.4
  - pip:
{% if cookiecutter.add_downloader == "yes" or cookiecutter.add_cleaner == "yes" %}    - click==7.0{% endif %}
{% if cookiecutter.add_tox == "yes" %}    - doc8==0.8.0
    - flake8==3.7.3
    - flake8-bugbear==18.8.0
    - flake8-builtins==1.4.1
    - flake8-commas==2.0.0
    - flake8-comprehensions==1.4.1
    - flake8-deprecated==1.3
    - flake8-docstrings==1.3.0
    - flake8-eradicate==0.2.0
    - flake8-print==3.1.0
    - flake8-quotes==1.0.0
    - flake8-rst-docstrings==0.0.8
    - flake8-todo==0.7
    - flake8-type-annotations==0.1.0{% endif %}
    - jupyterlab==0.35.4
    - matplotlib==3.0.2
    - nbsphinx==0.4.2
    - pandas==0.24.0
{% if cookiecutter.add_tox == "yes" %}    - pep8-naming==0.8.0{% endif %}
    - pre-commit==1.14.2
    - pybtex==0.22.2
    - pytest==4.2.0
    - pytest-cov==2.6.1
    - pytest-pythonpath==0.7.3
    - sphinx==1.8.3
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.2
    - sphinxcontrib-bibtex==0.4.2
{% if cookiecutter.add_downloader == "yes" %}    - tqdm==4.30.0{% endif %}
{% if cookiecutter.add_tox == "yes" %}    - tox==3.7.0{% endif %}
