notifications:
  - provider: Email
    on_build_failure: false
    on_build_success: false
    on_build_status_changed: false

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    # - MINICONDA: "C:\\Miniconda36"
    - MINICONDA: "C:\\Miniconda36-x64"
    # - MINICONDA: "C:\\Miniconda37"
    - MINICONDA: "C:\\Miniconda37-x64"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  # Add miniconda to PATH
  - ps: $env:PATH = "$env:MINICONDA;$env:MINICONDA\Scripts;$env:MINICONDA\bin;$env:PATH"
  # Set conda to always yes and print info
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - easy_install -U pip
  - pip install tox
  - python -c "import os; print(os.environ)"

build: false

test_script:
  - tox -e pytest
