name: cc
channels:
  - defaults
  - pscondaenvs
dependencies:
  - pscondaenvs=1.2.4
  - python=3.7
  - python-graphviz=0.8.4
  - pip:
    - black==18.9b0
    - click==7.0
    - doc8==0.8.0
    - flake8==3.7.5
    - flake8-bugbear==18.8.0
    - flake8-builtins==1.4.1
    - flake8-commas==2.0.0
    - flake8-comprehensions==2.0.0
    - flake8-deprecated==1.3
    - flake8-docstrings==1.3.0
    - flake8-eradicate==0.2.0
    - flake8-print==3.1.0
    - flake8-quotes==1.0.0
    - flake8-rst-docstrings==0.0.8
    - flake8-todo==0.7
    - flake8-type-annotations==0.1.0
    - jupyterlab==0.35.4
    - matplotlib==3.0.2
    - nbsphinx==0.4.2
    - pandas==0.24.1
    - pep8-naming==0.8.2
    - pre-commit==1.14.4
    - pybtex==0.22.2
    - pytest==4.2.0
    - pytest-cookies==0.3.0
    - pytest-cov==2.6.1
    - pytest-pythonpath==0.7.3
    - sphinx==1.8.4
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.2
    - sphinxcontrib-bibtex==0.4.2
    - tqdm==4.30.0
    - tox==3.7.0
