name: cc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - click
  - doc8
  - jupyterlab>=1.0.0
  - matplotlib
  - nbsphinx
  - pandas>=0.24
  - pybtex
  - pytest
  - pytest-cookies
  - pytest-cov
  - python-graphviz
  - restructuredtext_lint
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - tqdm
  - tox
  - pip:
    - pre-commit==1.18.2
