name: cc
channels:
  - defaults
  - pscondaenvs
dependencies:
  - pscondaenvs=1.2.4
  - python=3.7
  - python-graphviz=0.8.4
  - pip:
    - click==7.0
    - doc8==0.8.0
    - jupyterlab==0.35.4
    - matplotlib==3.0.3
    - nbsphinx==0.4.2
    - pandas==0.24.1
    - pre-commit==1.14.4
    - pybtex==0.22.2
    - pytest==4.3.0
    - pytest-cookies==0.3.0
    - pytest-cov==2.6.1
    - pytest-pythonpath==0.7.3
    - restructuredtext_lint==1.2.2
    - sphinx==1.8.4
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==0.4.2
    - tqdm==4.31.1
    - tox==3.7.0
